window.TEST_MATCH_INVINCIBLE_DATA = {
  sources: [
    {
      label: "MCC Law 16 - The result",
      url: "https://www.lords.org/mcc/the-laws/the-result",
      note: "Used for win, tie, draw, and outright result logic."
    },
    {
      label: "ESPNcricinfo Statsguru",
      url: "https://stats.espncricinfo.com/ci/engine/stats/index.html",
      note: "Recommended production source for all-era Test player records and filters."
    },
    {
      label: "Cricsheet match data",
      url: "https://cricsheet.org/downloads/",
      note: "Open structured ball-by-ball source for modern Test match modelling."
    },
    {
      label: "Cricsheet Register",
      url: "https://cricsheet.org/register/",
      note: "Open identifier mapping for Cricsheet, ESPNcricinfo, CricketArchive, and other ids."
    },
    {
      label: "Wikimedia Test cricketer country lists",
      url: "https://en.wikipedia.org/wiki/Lists_of_Test_cricketers",
      note: "Generated prototype roster source for every capped men's Test player by country and career span."
    }
  ],
  decades: [1870, 1880, 1890, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020],
  countries: ["Australia", "England", "India", "West Indies", "Pakistan", "South Africa", "New Zealand", "Sri Lanka", "Bangladesh", "Zimbabwe", "Afghanistan", "Ireland"],
  formations: [
    {
      id: "classic",
      name: "Classic Test XI",
      summary: "5 specialist batters, 1 all-rounder, 1 wicket keeper, 4 bowlers.",
      minSpinners: 1,
      slots: [
        { id: "opener1", label: "Opening bat 1", kind: "bat", tags: ["opener"] },
        { id: "opener2", label: "Opening bat 2", kind: "bat", tags: ["opener"] },
        { id: "no3", label: "No. 3", kind: "bat", tags: ["top-order"] },
        { id: "no4", label: "No. 4", kind: "bat", tags: ["middle-order"] },
        { id: "no5", label: "No. 5", kind: "bat", tags: ["middle-order"] },
        { id: "allrounder", label: "All-rounder", kind: "allrounder", tags: ["allrounder"] },
        { id: "keeper", label: "Wicket keeper", kind: "keeper", tags: ["keeper"] },
        { id: "bowler1", label: "Bowler 1", kind: "bowler", tags: ["bowler"] },
        { id: "bowler2", label: "Bowler 2", kind: "bowler", tags: ["bowler"] },
        { id: "bowler3", label: "Bowler 3", kind: "bowler", tags: ["bowler"] },
        { id: "bowler4", label: "Bowler 4", kind: "bowler", tags: ["bowler"] }
      ]
    },
    {
      id: "six-bat",
      name: "Six Batters",
      summary: "6 specialist batters, 1 wicket keeper, 4 bowlers. Safer batting, less fifth-bowling cover.",
      minSpinners: 1,
      slots: [
        { id: "opener1", label: "Opening bat 1", kind: "bat", tags: ["opener"] },
        { id: "opener2", label: "Opening bat 2", kind: "bat", tags: ["opener"] },
        { id: "no3", label: "No. 3", kind: "bat", tags: ["top-order"] },
        { id: "no4", label: "No. 4", kind: "bat", tags: ["middle-order"] },
        { id: "no5", label: "No. 5", kind: "bat", tags: ["middle-order"] },
        { id: "no6", label: "No. 6", kind: "bat", tags: ["middle-order"] },
        { id: "keeper", label: "Wicket keeper", kind: "keeper", tags: ["keeper"] },
        { id: "bowler1", label: "Bowler 1", kind: "bowler", tags: ["bowler"] },
        { id: "bowler2", label: "Bowler 2", kind: "bowler", tags: ["bowler"] },
        { id: "bowler3", label: "Bowler 3", kind: "bowler", tags: ["bowler"] },
        { id: "bowler4", label: "Bowler 4", kind: "bowler", tags: ["bowler"] }
      ]
    },
    {
      id: "two-allrounders",
      name: "Two All-rounders",
      summary: "5 batters, 2 all-rounders, 1 keeper, 3 bowlers. Strong balance, lower specialist bowling ceiling.",
      minSpinners: 1,
      slots: [
        { id: "opener1", label: "Opening bat 1", kind: "bat", tags: ["opener"] },
        { id: "opener2", label: "Opening bat 2", kind: "bat", tags: ["opener"] },
        { id: "no3", label: "No. 3", kind: "bat", tags: ["top-order"] },
        { id: "no4", label: "No. 4", kind: "bat", tags: ["middle-order"] },
        { id: "no5", label: "No. 5", kind: "bat", tags: ["middle-order"] },
        { id: "allrounder1", label: "All-rounder 1", kind: "allrounder", tags: ["allrounder"] },
        { id: "allrounder2", label: "All-rounder 2", kind: "allrounder", tags: ["allrounder"] },
        { id: "keeper", label: "Wicket keeper", kind: "keeper", tags: ["keeper"] },
        { id: "bowler1", label: "Bowler 1", kind: "bowler", tags: ["bowler"] },
        { id: "bowler2", label: "Bowler 2", kind: "bowler", tags: ["bowler"] },
        { id: "bowler3", label: "Bowler 3", kind: "bowler", tags: ["bowler"] }
      ]
    },
    {
      id: "spin-twin",
      name: "Spin Twin",
      summary: "5 batters, 1 all-rounder, 1 keeper, 2 quicks, 2 spinners.",
      minSpinners: 2,
      slots: [
        { id: "opener1", label: "Opening bat 1", kind: "bat", tags: ["opener"] },
        { id: "opener2", label: "Opening bat 2", kind: "bat", tags: ["opener"] },
        { id: "no3", label: "No. 3", kind: "bat", tags: ["top-order"] },
        { id: "no4", label: "No. 4", kind: "bat", tags: ["middle-order"] },
        { id: "no5", label: "No. 5", kind: "bat", tags: ["middle-order"] },
        { id: "allrounder", label: "All-rounder", kind: "allrounder", tags: ["allrounder"] },
        { id: "keeper", label: "Wicket keeper", kind: "keeper", tags: ["keeper"] },
        { id: "quick1", label: "Fast bowler 1", kind: "pace", tags: ["pace"] },
        { id: "quick2", label: "Fast bowler 2", kind: "pace", tags: ["pace"] },
        { id: "spinner1", label: "Spinner 1", kind: "spinner", tags: ["spinner"] },
        { id: "spinner2", label: "Spinner 2", kind: "spinner", tags: ["spinner"] }
      ]
    }
  ],
  grounds: [
    { name: "Lord's", city: "London", country: "England", pitch: "Lord's slope with seam early and value for patience", pace: 1.12, spin: 0.92, batting: 0.98, rain: 0.22, weather: ["Bright intervals", "Overcast", "Light showers"] },
    { name: "The Oval", city: "London", country: "England", pitch: "True bounce that can flatten before late spin", pace: 1.02, spin: 1.04, batting: 1.08, rain: 0.18, weather: ["Bright intervals", "Overcast", "Dry breeze"] },
    { name: "Old Trafford", city: "Manchester", country: "England", pitch: "Seam-friendly weather with late rough for spinners", pace: 1.10, spin: 1.04, batting: 0.98, rain: 0.24, weather: ["Overcast", "Light showers", "Bright intervals"] },
    { name: "Headingley", city: "Leeds", country: "England", pitch: "Clouds, swing, and sudden batting collapses", pace: 1.18, spin: 0.88, batting: 0.94, rain: 0.22, weather: ["Overcast", "Windy", "Light showers"] },
    { name: "Edgbaston", city: "Birmingham", country: "England", pitch: "Balanced surface with noisy pressure moments", pace: 1.06, spin: 0.98, batting: 1.02, rain: 0.18, weather: ["Bright intervals", "Overcast", "Dry breeze"] },
    { name: "Trent Bridge", city: "Nottingham", country: "England", pitch: "Swing and seam if the clouds settle in", pace: 1.16, spin: 0.86, batting: 0.96, rain: 0.20, weather: ["Overcast", "Light showers", "Bright intervals"] },
    { name: "Melbourne Cricket Ground", city: "Melbourne", country: "Australia", pitch: "Large square, hard length, reverse-swing later", pace: 1.04, spin: 0.98, batting: 1.04, rain: 0.12, weather: ["Bright", "Hot and dry", "Late cloud"] },
    { name: "Sydney Cricket Ground", city: "Sydney", country: "Australia", pitch: "Classical wear, footmarks, and late turn", pace: 0.96, spin: 1.18, batting: 1.02, rain: 0.14, weather: ["Humid", "Bright", "Thunder threat"] },
    { name: "Adelaide Oval", city: "Adelaide", country: "Australia", pitch: "Friendly batting surface that rewards relentless accuracy", pace: 0.98, spin: 1.06, batting: 1.12, rain: 0.08, weather: ["Hot and dry", "Bright", "Dry breeze"] },
    { name: "The Gabba", city: "Brisbane", country: "Australia", pitch: "Carry, bounce, and hard new-ball work", pace: 1.18, spin: 0.88, batting: 1.00, rain: 0.18, weather: ["Humid", "Bright", "Afternoon storm"] },
    { name: "Perth Stadium", city: "Perth", country: "Australia", pitch: "Fast bounce, heat, and long spells into the breeze", pace: 1.24, spin: 0.82, batting: 0.98, rain: 0.07, weather: ["Hot and dry", "Bright", "Dry breeze"] },
    { name: "Eden Gardens", city: "Kolkata", country: "India", pitch: "Slow burn into turn with a loud fifth-day finish", pace: 0.90, spin: 1.20, batting: 1.04, rain: 0.10, weather: ["Hazy sun", "Humid", "Dry heat"] },
    { name: "MA Chidambaram Stadium", city: "Chennai", country: "India", pitch: "Hot, dry, and demanding against spin", pace: 0.84, spin: 1.30, batting: 0.96, rain: 0.08, weather: ["Hot and dry", "Hazy sun", "Sea breeze"] },
    { name: "Wankhede Stadium", city: "Mumbai", country: "India", pitch: "Coastal swing early before batting speeds up", pace: 1.02, spin: 1.04, batting: 1.06, rain: 0.10, weather: ["Humid", "Sea breeze", "Hazy sun"] },
    { name: "Arun Jaitley Stadium", city: "Delhi", country: "India", pitch: "Low bounce and sharp spin as the match wears on", pace: 0.82, spin: 1.28, batting: 0.94, rain: 0.06, weather: ["Hazy sun", "Hot and dry", "Dry heat"] },
    { name: "M. Chinnaswamy Stadium", city: "Bengaluru", country: "India", pitch: "Quick scoring ground with enough carry for seamers", pace: 1.00, spin: 1.02, batting: 1.12, rain: 0.12, weather: ["Bright", "Cloud build-up", "Dry breeze"] },
    { name: "Narendra Modi Stadium", city: "Ahmedabad", country: "India", pitch: "Dry surface where pace fades and spin grows", pace: 0.88, spin: 1.22, batting: 1.00, rain: 0.05, weather: ["Hot and dry", "Hazy sun", "Dry heat"] },
    { name: "Galle International Stadium", city: "Galle", country: "Sri Lanka", pitch: "Coastal turner with fast-scoring windows", pace: 0.84, spin: 1.34, batting: 0.98, rain: 0.20, weather: ["Humid", "Sea breeze", "Tropical showers"] },
    { name: "Sinhalese Sports Club", city: "Colombo", country: "Sri Lanka", pitch: "Batting value early, spin pressure late", pace: 0.88, spin: 1.18, batting: 1.06, rain: 0.18, weather: ["Humid", "Hazy sun", "Tropical showers"] },
    { name: "Pallekele Stadium", city: "Kandy", country: "Sri Lanka", pitch: "Hill-country pace carry before the surface slows", pace: 0.98, spin: 1.10, batting: 1.00, rain: 0.20, weather: ["Humid", "Cloud build-up", "Tropical showers"] },
    { name: "P Sara Oval", city: "Colombo", country: "Sri Lanka", pitch: "Traditional surface with reverse swing and late turn", pace: 0.92, spin: 1.16, batting: 1.00, rain: 0.18, weather: ["Humid", "Sea breeze", "Hazy sun"] },
    { name: "Asgiriya Stadium", city: "Kandy", country: "Sri Lanka", pitch: "Older-style surface with movement and variable bounce", pace: 1.00, spin: 1.08, batting: 0.96, rain: 0.22, weather: ["Cloud build-up", "Humid", "Tropical showers"] },
    { name: "Newlands", city: "Cape Town", country: "South Africa", pitch: "New-ball nip and clean stroke value", pace: 1.16, spin: 0.86, batting: 0.98, rain: 0.12, weather: ["Bright", "Mountain cloud", "Dry breeze"] },
    { name: "The Wanderers", city: "Johannesburg", country: "South Africa", pitch: "Highveld pace, bounce, and collapsing sessions", pace: 1.24, spin: 0.80, batting: 0.94, rain: 0.15, weather: ["Bright", "Thunder threat", "Dry heat"] },
    { name: "SuperSport Park", city: "Centurion", country: "South Africa", pitch: "Steep bounce and new-ball danger", pace: 1.20, spin: 0.82, batting: 0.98, rain: 0.15, weather: ["Bright", "Thunder threat", "Dry heat"] },
    { name: "Kingsmead", city: "Durban", country: "South Africa", pitch: "Coastal humidity with seam and slower wear", pace: 1.12, spin: 0.92, batting: 0.96, rain: 0.18, weather: ["Humid", "Sea breeze", "Cloud build-up"] },
    { name: "St George's Park", city: "Gqeberha", country: "South Africa", pitch: "Old-school patience pitch with reverse swing windows", pace: 1.06, spin: 0.96, batting: 0.98, rain: 0.14, weather: ["Bright", "Dry breeze", "Cloud build-up"] },
    { name: "Basin Reserve", city: "Wellington", country: "New Zealand", pitch: "Wind, seam, and patience under clouds", pace: 1.20, spin: 0.82, batting: 0.94, rain: 0.24, weather: ["Overcast", "Windy", "Light showers"] },
    { name: "Hagley Oval", city: "Christchurch", country: "New Zealand", pitch: "Green tinge and honest bounce for seamers", pace: 1.18, spin: 0.84, batting: 0.98, rain: 0.18, weather: ["Overcast", "Bright intervals", "Windy"] },
    { name: "Eden Park", city: "Auckland", country: "New Zealand", pitch: "Short square boundaries and swing in humid air", pace: 1.10, spin: 0.88, batting: 1.04, rain: 0.22, weather: ["Humid", "Overcast", "Light showers"] },
    { name: "Seddon Park", city: "Hamilton", country: "New Zealand", pitch: "Batting-friendly once the new ball softens", pace: 1.06, spin: 0.90, batting: 1.08, rain: 0.18, weather: ["Bright intervals", "Overcast", "Dry breeze"] },
    { name: "University Oval", city: "Dunedin", country: "New Zealand", pitch: "Cool air, movement, and attritional scoring", pace: 1.14, spin: 0.82, batting: 0.96, rain: 0.20, weather: ["Overcast", "Windy", "Light showers"] },
    { name: "Sabina Park", city: "Kingston", country: "West Indies", pitch: "Fast deck with uneven bounce when it wears", pace: 1.20, spin: 0.88, batting: 0.96, rain: 0.16, weather: ["Bright", "Humid", "Tropical showers"] },
    { name: "Kensington Oval", city: "Bridgetown", country: "West Indies", pitch: "Breezy pace early, then hard-work batting", pace: 1.12, spin: 0.94, batting: 1.00, rain: 0.15, weather: ["Sea breeze", "Bright", "Brief showers"] },
    { name: "Queen's Park Oval", city: "Port of Spain", country: "West Indies", pitch: "Dry Caribbean surface that can take spin", pace: 0.98, spin: 1.12, batting: 1.04, rain: 0.18, weather: ["Humid", "Bright", "Tropical showers"] },
    { name: "Sir Vivian Richards Stadium", city: "North Sound", country: "West Indies", pitch: "Slow surface with crosswind and attrition", pace: 1.02, spin: 1.02, batting: 0.98, rain: 0.16, weather: ["Sea breeze", "Bright", "Brief showers"] },
    { name: "Bourda", city: "Georgetown", country: "West Indies", pitch: "Low bounce and old-style spin pressure", pace: 0.92, spin: 1.16, batting: 0.98, rain: 0.22, weather: ["Humid", "Tropical showers", "Hazy sun"] },
    { name: "National Stadium", city: "Karachi", country: "Pakistan", pitch: "Dry heat, reverse swing, and late spin", pace: 0.98, spin: 1.16, batting: 1.06, rain: 0.05, weather: ["Hot and dry", "Hazy sun", "Dry breeze"] },
    { name: "Gaddafi Stadium", city: "Lahore", country: "Pakistan", pitch: "Flat early, abrasive later, reverse swing in play", pace: 1.00, spin: 1.10, batting: 1.08, rain: 0.08, weather: ["Hot and dry", "Hazy sun", "Cool evening"] },
    { name: "Rawalpindi Cricket Stadium", city: "Rawalpindi", country: "Pakistan", pitch: "Seam early before turning into a dry grind", pace: 1.06, spin: 1.02, batting: 1.04, rain: 0.10, weather: ["Hazy sun", "Cool evening", "Dry breeze"] },
    { name: "Multan Cricket Stadium", city: "Multan", country: "Pakistan", pitch: "Hot, flat, and abrasive enough for reverse swing", pace: 0.96, spin: 1.14, batting: 1.08, rain: 0.04, weather: ["Hot and dry", "Hazy sun", "Dry heat"] },
    { name: "Iqbal Stadium", city: "Faisalabad", country: "Pakistan", pitch: "Slow surface that can become a long batting examination", pace: 0.94, spin: 1.08, batting: 1.06, rain: 0.06, weather: ["Hot and dry", "Hazy sun", "Dry breeze"] }
  ],
  historicalTeams: [
    {
      id: "aus-1948",
      country: "Australia",
      year: 1948,
      name: "Australia 1948",
      nickname: "Bradman's touring machine",
      batting: 96,
      pace: 90,
      spin: 82,
      fielding: 93,
      resilience: 96,
      xi: ["Sid Barnes", "Arthur Morris", "Don Bradman", "Lindsay Hassett", "Neil Harvey", "Keith Miller", "Sam Loxton", "Don Tallon", "Ray Lindwall", "Bill Johnston", "Ernie Toshack"],
      bowlers: [
        { name: "Ray Lindwall", style: "pace", rating: 95 },
        { name: "Keith Miller", style: "pace", rating: 92 },
        { name: "Bill Johnston", style: "left-arm pace", rating: 86 },
        { name: "Ernie Toshack", style: "left-arm seam", rating: 82 }
      ]
    },
    {
      id: "wi-1984",
      country: "West Indies",
      year: 1984,
      name: "West Indies 1984",
      nickname: "Four-pronged pace storm",
      batting: 93,
      pace: 99,
      spin: 58,
      fielding: 90,
      resilience: 94,
      xi: ["Gordon Greenidge", "Desmond Haynes", "Richie Richardson", "Viv Richards", "Clive Lloyd", "Larry Gomes", "Jeff Dujon", "Malcolm Marshall", "Michael Holding", "Joel Garner", "Courtney Walsh"],
      bowlers: [
        { name: "Malcolm Marshall", style: "pace", rating: 99 },
        { name: "Michael Holding", style: "pace", rating: 95 },
        { name: "Joel Garner", style: "pace", rating: 94 },
        { name: "Courtney Walsh", style: "pace", rating: 91 }
      ]
    },
    {
      id: "aus-2001",
      country: "Australia",
      year: 2001,
      name: "Australia 2001",
      nickname: "Waugh-era pressure",
      batting: 95,
      pace: 94,
      spin: 98,
      fielding: 95,
      resilience: 94,
      xi: ["Matthew Hayden", "Justin Langer", "Ricky Ponting", "Mark Waugh", "Steve Waugh", "Damien Martyn", "Adam Gilchrist", "Shane Warne", "Brett Lee", "Jason Gillespie", "Glenn McGrath"],
      bowlers: [
        { name: "Glenn McGrath", style: "pace", rating: 98 },
        { name: "Jason Gillespie", style: "pace", rating: 89 },
        { name: "Brett Lee", style: "pace", rating: 88 },
        { name: "Shane Warne", style: "spin", rating: 99 }
      ]
    },
    {
      id: "ind-2021",
      country: "India",
      year: 2021,
      name: "India 2021",
      nickname: "Pace depth plus elite spin",
      batting: 90,
      pace: 91,
      spin: 97,
      fielding: 90,
      resilience: 95,
      xi: ["Rohit Sharma", "Shubman Gill", "Cheteshwar Pujara", "Virat Kohli", "Ajinkya Rahane", "Rishabh Pant", "Ravindra Jadeja", "Ravichandran Ashwin", "Mohammed Shami", "Ishant Sharma", "Jasprit Bumrah"],
      bowlers: [
        { name: "Jasprit Bumrah", style: "pace", rating: 97 },
        { name: "Mohammed Shami", style: "pace", rating: 91 },
        { name: "Ishant Sharma", style: "pace", rating: 85 },
        { name: "Ravichandran Ashwin", style: "spin", rating: 98 },
        { name: "Ravindra Jadeja", style: "spin", rating: 91 }
      ]
    },
    {
      id: "eng-2011",
      country: "England",
      year: 2011,
      name: "England 2011",
      nickname: "Cook, swing, and control",
      batting: 90,
      pace: 91,
      spin: 82,
      fielding: 88,
      resilience: 88,
      xi: ["Andrew Strauss", "Alastair Cook", "Jonathan Trott", "Kevin Pietersen", "Ian Bell", "Eoin Morgan", "Matt Prior", "Stuart Broad", "Graeme Swann", "Tim Bresnan", "James Anderson"],
      bowlers: [
        { name: "James Anderson", style: "pace", rating: 94 },
        { name: "Stuart Broad", style: "pace", rating: 90 },
        { name: "Tim Bresnan", style: "pace", rating: 82 },
        { name: "Graeme Swann", style: "spin", rating: 88 }
      ]
    },
    {
      id: "sa-2012",
      country: "South Africa",
      year: 2012,
      name: "South Africa 2012",
      nickname: "Kallis, Amla, Steyn, Philander",
      batting: 94,
      pace: 97,
      spin: 64,
      fielding: 91,
      resilience: 92,
      xi: ["Graeme Smith", "Alviro Petersen", "Hashim Amla", "Jacques Kallis", "AB de Villiers", "Jacques Rudolph", "JP Duminy", "Vernon Philander", "Dale Steyn", "Morne Morkel", "Imran Tahir"],
      bowlers: [
        { name: "Dale Steyn", style: "pace", rating: 99 },
        { name: "Vernon Philander", style: "pace", rating: 94 },
        { name: "Morne Morkel", style: "pace", rating: 88 },
        { name: "Imran Tahir", style: "spin", rating: 76 }
      ]
    },
    {
      id: "pak-1992",
      country: "Pakistan",
      year: 1992,
      name: "Pakistan 1992",
      nickname: "Reverse swing and wrist-spin threat",
      batting: 87,
      pace: 97,
      spin: 89,
      fielding: 82,
      resilience: 88,
      xi: ["Aamer Sohail", "Rameez Raja", "Javed Miandad", "Saleem Malik", "Inzamam-ul-Haq", "Wasim Akram", "Moin Khan", "Imran Khan", "Waqar Younis", "Mushtaq Ahmed", "Aaqib Javed"],
      bowlers: [
        { name: "Wasim Akram", style: "pace", rating: 98 },
        { name: "Waqar Younis", style: "pace", rating: 96 },
        { name: "Imran Khan", style: "pace", rating: 91 },
        { name: "Mushtaq Ahmed", style: "spin", rating: 85 }
      ]
    },
    {
      id: "sl-2007",
      country: "Sri Lanka",
      year: 2007,
      name: "Sri Lanka 2007",
      nickname: "Sangakkara, Jayawardene, and Murali",
      batting: 91,
      pace: 82,
      spin: 99,
      fielding: 86,
      resilience: 89,
      xi: ["Sanath Jayasuriya", "Michael Vandort", "Kumar Sangakkara", "Mahela Jayawardene", "Thilan Samaraweera", "Tillakaratne Dilshan", "Prasanna Jayawardene", "Chaminda Vaas", "Lasith Malinga", "Muttiah Muralitharan", "Dilhara Fernando"],
      bowlers: [
        { name: "Muttiah Muralitharan", style: "spin", rating: 99 },
        { name: "Chaminda Vaas", style: "pace", rating: 88 },
        { name: "Lasith Malinga", style: "pace", rating: 82 },
        { name: "Tillakaratne Dilshan", style: "spin", rating: 70 }
      ]
    },
    {
      id: "nz-2021",
      country: "New Zealand",
      year: 2021,
      name: "New Zealand 2021",
      nickname: "World Test Championship control",
      batting: 89,
      pace: 93,
      spin: 74,
      fielding: 90,
      resilience: 91,
      xi: ["Tom Latham", "Devon Conway", "Kane Williamson", "Ross Taylor", "Henry Nicholls", "BJ Watling", "Colin de Grandhomme", "Kyle Jamieson", "Tim Southee", "Neil Wagner", "Trent Boult"],
      bowlers: [
        { name: "Tim Southee", style: "pace", rating: 90 },
        { name: "Trent Boult", style: "pace", rating: 92 },
        { name: "Kyle Jamieson", style: "pace", rating: 88 },
        { name: "Neil Wagner", style: "pace", rating: 89 }
      ]
    }
  ],
  players: [
    { id: "charles-bannerman", name: "Charles Bannerman", country: "Australia", decade: 1870, roles: ["bat"], tags: ["opener"], bat: 83, bowl: 8, keep: 0, field: 70, style: "part-time", temperament: 88 },
    { id: "billy-murdoch", name: "Billy Murdoch", country: "Australia", decade: 1880, roles: ["bat", "keeper"], tags: ["opener", "keeper"], bat: 82, bowl: 5, keep: 76, field: 72, style: "part-time", temperament: 84 },
    { id: "wg-grace", name: "W. G. Grace", country: "England", decade: 1880, roles: ["bat", "allrounder"], tags: ["opener", "allrounder"], bat: 85, bowl: 70, keep: 0, field: 76, style: "seam", temperament: 90 },
    { id: "arthur-shrewsbury", name: "Arthur Shrewsbury", country: "England", decade: 1890, roles: ["bat"], tags: ["top-order"], bat: 84, bowl: 8, keep: 0, field: 72, style: "part-time", temperament: 88 },
    { id: "victor-trumper", name: "Victor Trumper", country: "Australia", decade: 1900, roles: ["bat"], tags: ["opener", "middle-order"], bat: 90, bowl: 14, keep: 0, field: 82, style: "part-time", temperament: 92 },
    { id: "aubrey-faulkner", name: "Aubrey Faulkner", country: "South Africa", decade: 1910, roles: ["allrounder", "spinner"], tags: ["allrounder", "spinner"], bat: 82, bowl: 88, keep: 0, field: 78, style: "spin", temperament: 87 },
    { id: "jack-hobbs", name: "Jack Hobbs", country: "England", decade: 1910, roles: ["bat"], tags: ["opener"], bat: 94, bowl: 12, keep: 0, field: 82, style: "part-time", temperament: 96 },
    { id: "sydney-barnes", name: "Sydney Barnes", country: "England", decade: 1910, roles: ["bowler"], tags: ["bowler"], bat: 30, bowl: 98, keep: 0, field: 78, style: "seam", temperament: 94 },
    { id: "herbert-sutcliffe", name: "Herbert Sutcliffe", country: "England", decade: 1920, roles: ["bat"], tags: ["opener"], bat: 93, bowl: 7, keep: 0, field: 80, style: "part-time", temperament: 96 },
    { id: "learie-constantine", name: "Learie Constantine", country: "West Indies", decade: 1920, roles: ["allrounder", "bowler"], tags: ["allrounder", "pace"], bat: 76, bowl: 84, keep: 0, field: 90, style: "pace", temperament: 88 },
    { id: "bill-ponsford", name: "Bill Ponsford", country: "Australia", decade: 1920, roles: ["bat"], tags: ["opener"], bat: 88, bowl: 6, keep: 0, field: 76, style: "part-time", temperament: 88 },
    { id: "jack-gregory", name: "Jack Gregory", country: "Australia", decade: 1920, roles: ["allrounder", "bowler"], tags: ["allrounder", "pace"], bat: 75, bowl: 86, keep: 0, field: 86, style: "pace", temperament: 84 },
    { id: "don-bradman", name: "Don Bradman", country: "Australia", decade: 1930, roles: ["bat"], tags: ["top-order", "middle-order"], bat: 100, bowl: 18, keep: 0, field: 82, style: "part-time", temperament: 100 },
    { id: "wally-hammond", name: "Wally Hammond", country: "England", decade: 1930, roles: ["bat", "allrounder"], tags: ["top-order", "allrounder"], bat: 95, bowl: 62, keep: 0, field: 88, style: "seam", temperament: 93 },
    { id: "george-headley", name: "George Headley", country: "West Indies", decade: 1930, roles: ["bat"], tags: ["top-order"], bat: 94, bowl: 10, keep: 0, field: 78, style: "part-time", temperament: 96 },
    { id: "bill-oreilly", name: "Bill O'Reilly", country: "Australia", decade: 1930, roles: ["bowler", "spinner"], tags: ["spinner"], bat: 28, bowl: 96, keep: 0, field: 76, style: "spin", temperament: 93 },
    { id: "len-hutton", name: "Len Hutton", country: "England", decade: 1940, roles: ["bat"], tags: ["opener"], bat: 94, bowl: 8, keep: 0, field: 80, style: "part-time", temperament: 96 },
    { id: "keith-miller", name: "Keith Miller", country: "Australia", decade: 1940, roles: ["allrounder", "bowler"], tags: ["allrounder", "pace"], bat: 86, bowl: 90, keep: 0, field: 87, style: "pace", temperament: 90 },
    { id: "ray-lindwall", name: "Ray Lindwall", country: "Australia", decade: 1940, roles: ["bowler"], tags: ["pace"], bat: 42, bowl: 94, keep: 0, field: 80, style: "pace", temperament: 91 },
    { id: "vijay-merchant", name: "Vijay Merchant", country: "India", decade: 1940, roles: ["bat"], tags: ["opener"], bat: 90, bowl: 8, keep: 0, field: 76, style: "part-time", temperament: 93 },
    { id: "dudley-nourse", name: "Dudley Nourse", country: "South Africa", decade: 1940, roles: ["bat"], tags: ["middle-order"], bat: 87, bowl: 10, keep: 0, field: 75, style: "part-time", temperament: 88 },
    { id: "neil-harvey", name: "Neil Harvey", country: "Australia", decade: 1950, roles: ["bat"], tags: ["middle-order"], bat: 91, bowl: 12, keep: 0, field: 88, style: "part-time", temperament: 90 },
    { id: "richie-benaud", name: "Richie Benaud", country: "Australia", decade: 1950, roles: ["allrounder", "spinner", "bowler"], tags: ["allrounder", "spinner"], bat: 73, bowl: 90, keep: 0, field: 86, style: "spin", temperament: 90 },
    { id: "jim-laker", name: "Jim Laker", country: "England", decade: 1950, roles: ["bowler", "spinner"], tags: ["spinner"], bat: 32, bowl: 94, keep: 0, field: 78, style: "spin", temperament: 90 },
    { id: "fred-trueman", name: "Fred Trueman", country: "England", decade: 1950, roles: ["bowler"], tags: ["pace"], bat: 36, bowl: 93, keep: 0, field: 82, style: "pace", temperament: 90 },
    { id: "frank-worrell", name: "Frank Worrell", country: "West Indies", decade: 1950, roles: ["bat", "allrounder"], tags: ["middle-order", "allrounder"], bat: 88, bowl: 64, keep: 0, field: 85, style: "seam", temperament: 94 },
    { id: "vinoo-mankad", name: "Vinoo Mankad", country: "India", decade: 1950, roles: ["allrounder", "spinner"], tags: ["opener", "allrounder", "spinner"], bat: 80, bowl: 88, keep: 0, field: 80, style: "spin", temperament: 88 },
    { id: "hanif-mohammad", name: "Hanif Mohammad", country: "Pakistan", decade: 1950, roles: ["bat"], tags: ["opener"], bat: 89, bowl: 7, keep: 0, field: 78, style: "part-time", temperament: 96 },
    { id: "fazal-mahmood", name: "Fazal Mahmood", country: "Pakistan", decade: 1950, roles: ["bowler"], tags: ["pace"], bat: 30, bowl: 91, keep: 0, field: 76, style: "pace", temperament: 91 },
    { id: "bert-sutcliffe", name: "Bert Sutcliffe", country: "New Zealand", decade: 1950, roles: ["bat"], tags: ["top-order"], bat: 86, bowl: 6, keep: 0, field: 75, style: "part-time", temperament: 92 },
    { id: "garfield-sobers", name: "Garfield Sobers", country: "West Indies", decade: 1960, roles: ["allrounder", "spinner", "bowler", "bat"], tags: ["middle-order", "allrounder", "spinner"], bat: 96, bowl: 88, keep: 0, field: 90, style: "spin", temperament: 96 },
    { id: "rohan-kanhai", name: "Rohan Kanhai", country: "West Indies", decade: 1960, roles: ["bat"], tags: ["middle-order"], bat: 90, bowl: 8, keep: 0, field: 82, style: "part-time", temperament: 88 },
    { id: "graeme-pollock", name: "Graeme Pollock", country: "South Africa", decade: 1960, roles: ["bat"], tags: ["middle-order"], bat: 94, bowl: 12, keep: 0, field: 82, style: "part-time", temperament: 92 },
    { id: "bob-simpson", name: "Bob Simpson", country: "Australia", decade: 1960, roles: ["bat", "spinner"], tags: ["opener", "spinner"], bat: 86, bowl: 66, keep: 0, field: 88, style: "spin", temperament: 90 },
    { id: "barry-richards", name: "Barry Richards", country: "South Africa", decade: 1970, roles: ["bat"], tags: ["opener"], bat: 93, bowl: 12, keep: 0, field: 82, style: "part-time", temperament: 90 },
    { id: "mike-procter", name: "Mike Procter", country: "South Africa", decade: 1970, roles: ["allrounder", "bowler"], tags: ["allrounder", "pace"], bat: 82, bowl: 92, keep: 0, field: 84, style: "pace", temperament: 90 },
    { id: "sunil-gavaskar", name: "Sunil Gavaskar", country: "India", decade: 1970, roles: ["bat"], tags: ["opener"], bat: 94, bowl: 6, keep: 0, field: 78, style: "part-time", temperament: 96 },
    { id: "bishan-bedi", name: "Bishan Bedi", country: "India", decade: 1970, roles: ["bowler", "spinner"], tags: ["spinner"], bat: 24, bowl: 91, keep: 0, field: 75, style: "spin", temperament: 90 },
    { id: "greg-chappell", name: "Greg Chappell", country: "Australia", decade: 1970, roles: ["bat"], tags: ["middle-order"], bat: 93, bowl: 36, keep: 0, field: 88, style: "seam", temperament: 92 },
    { id: "dennis-lillee", name: "Dennis Lillee", country: "Australia", decade: 1970, roles: ["bowler"], tags: ["pace"], bat: 33, bowl: 96, keep: 0, field: 80, style: "pace", temperament: 94 },
    { id: "clive-lloyd", name: "Clive Lloyd", country: "West Indies", decade: 1970, roles: ["bat"], tags: ["middle-order"], bat: 90, bowl: 12, keep: 0, field: 84, style: "part-time", temperament: 92 },
    { id: "andy-roberts", name: "Andy Roberts", country: "West Indies", decade: 1970, roles: ["bowler"], tags: ["pace"], bat: 34, bowl: 93, keep: 0, field: 78, style: "pace", temperament: 91 },
    { id: "geoffrey-boycott", name: "Geoffrey Boycott", country: "England", decade: 1970, roles: ["bat"], tags: ["opener"], bat: 90, bowl: 7, keep: 0, field: 78, style: "part-time", temperament: 96 },
    { id: "ian-botham", name: "Ian Botham", country: "England", decade: 1980, roles: ["allrounder", "bowler"], tags: ["allrounder", "pace"], bat: 84, bowl: 89, keep: 0, field: 88, style: "pace", temperament: 88 },
    { id: "david-gower", name: "David Gower", country: "England", decade: 1980, roles: ["bat"], tags: ["middle-order"], bat: 88, bowl: 6, keep: 0, field: 80, style: "part-time", temperament: 86 },
    { id: "viv-richards", name: "Viv Richards", country: "West Indies", decade: 1980, roles: ["bat"], tags: ["middle-order"], bat: 96, bowl: 28, keep: 0, field: 90, style: "part-time", temperament: 96 },
    { id: "malcolm-marshall", name: "Malcolm Marshall", country: "West Indies", decade: 1980, roles: ["bowler"], tags: ["pace"], bat: 44, bowl: 99, keep: 0, field: 82, style: "pace", temperament: 96 },
    { id: "imran-khan", name: "Imran Khan", country: "Pakistan", decade: 1980, roles: ["allrounder", "bowler"], tags: ["allrounder", "pace"], bat: 86, bowl: 94, keep: 0, field: 84, style: "pace", temperament: 95 },
    { id: "javed-miandad", name: "Javed Miandad", country: "Pakistan", decade: 1980, roles: ["bat"], tags: ["middle-order"], bat: 93, bowl: 12, keep: 0, field: 82, style: "part-time", temperament: 95 },
    { id: "abdul-qadir", name: "Abdul Qadir", country: "Pakistan", decade: 1980, roles: ["bowler", "spinner"], tags: ["spinner"], bat: 32, bowl: 90, keep: 0, field: 78, style: "spin", temperament: 89 },
    { id: "kapil-dev", name: "Kapil Dev", country: "India", decade: 1980, roles: ["allrounder", "bowler"], tags: ["allrounder", "pace"], bat: 82, bowl: 91, keep: 0, field: 86, style: "pace", temperament: 92 },
    { id: "allan-border", name: "Allan Border", country: "Australia", decade: 1980, roles: ["bat"], tags: ["middle-order"], bat: 92, bowl: 42, keep: 0, field: 84, style: "spin", temperament: 96 },
    { id: "richard-hadlee", name: "Richard Hadlee", country: "New Zealand", decade: 1980, roles: ["allrounder", "bowler"], tags: ["allrounder", "pace"], bat: 76, bowl: 96, keep: 0, field: 82, style: "pace", temperament: 94 },
    { id: "sachin-tendulkar", name: "Sachin Tendulkar", country: "India", decade: 1990, roles: ["bat"], tags: ["top-order", "middle-order"], bat: 96, bowl: 36, keep: 0, field: 88, style: "spin", temperament: 97 },
    { id: "brian-lara", name: "Brian Lara", country: "West Indies", decade: 1990, roles: ["bat"], tags: ["top-order", "middle-order"], bat: 96, bowl: 8, keep: 0, field: 82, style: "part-time", temperament: 94 },
    { id: "curtly-ambrose", name: "Curtly Ambrose", country: "West Indies", decade: 1990, roles: ["bowler"], tags: ["pace"], bat: 24, bowl: 97, keep: 0, field: 80, style: "pace", temperament: 95 },
    { id: "shane-warne", name: "Shane Warne", country: "Australia", decade: 1990, roles: ["bowler", "spinner"], tags: ["spinner"], bat: 42, bowl: 99, keep: 0, field: 84, style: "spin", temperament: 96 },
    { id: "glenn-mcgrath", name: "Glenn McGrath", country: "Australia", decade: 1990, roles: ["bowler"], tags: ["pace"], bat: 18, bowl: 98, keep: 0, field: 78, style: "pace", temperament: 96 },
    { id: "allan-donald", name: "Allan Donald", country: "South Africa", decade: 1990, roles: ["bowler"], tags: ["pace"], bat: 20, bowl: 94, keep: 0, field: 78, style: "pace", temperament: 91 },
    { id: "wasim-akram", name: "Wasim Akram", country: "Pakistan", decade: 1990, roles: ["allrounder", "bowler"], tags: ["allrounder", "pace"], bat: 70, bowl: 98, keep: 0, field: 82, style: "pace", temperament: 93 },
    { id: "waqar-younis", name: "Waqar Younis", country: "Pakistan", decade: 1990, roles: ["bowler"], tags: ["pace"], bat: 24, bowl: 96, keep: 0, field: 76, style: "pace", temperament: 91 },
    { id: "saqlain-mushtaq", name: "Saqlain Mushtaq", country: "Pakistan", decade: 1990, roles: ["bowler", "spinner"], tags: ["spinner"], bat: 32, bowl: 90, keep: 0, field: 78, style: "spin", temperament: 88 },
    { id: "martin-crowe", name: "Martin Crowe", country: "New Zealand", decade: 1990, roles: ["bat"], tags: ["middle-order"], bat: 90, bowl: 8, keep: 0, field: 80, style: "part-time", temperament: 90 },
    { id: "sanath-jayasuriya", name: "Sanath Jayasuriya", country: "Sri Lanka", decade: 1990, roles: ["bat", "allrounder", "spinner"], tags: ["opener", "allrounder", "spinner"], bat: 84, bowl: 76, keep: 0, field: 84, style: "spin", temperament: 86 },
    { id: "aravinda-de-silva", name: "Aravinda de Silva", country: "Sri Lanka", decade: 1990, roles: ["bat", "spinner"], tags: ["middle-order"], bat: 88, bowl: 48, keep: 0, field: 80, style: "spin", temperament: 88 },
    { id: "andy-flower", name: "Andy Flower", country: "Zimbabwe", decade: 1990, roles: ["bat", "keeper"], tags: ["middle-order", "keeper"], bat: 91, bowl: 4, keep: 84, field: 78, style: "part-time", temperament: 94 },
    { id: "heath-streak", name: "Heath Streak", country: "Zimbabwe", decade: 1990, roles: ["allrounder", "bowler"], tags: ["allrounder", "pace"], bat: 68, bowl: 84, keep: 0, field: 80, style: "pace", temperament: 86 },
    { id: "ricky-ponting", name: "Ricky Ponting", country: "Australia", decade: 2000, roles: ["bat"], tags: ["top-order"], bat: 95, bowl: 10, keep: 0, field: 94, style: "part-time", temperament: 94 },
    { id: "adam-gilchrist", name: "Adam Gilchrist", country: "Australia", decade: 2000, roles: ["keeper", "bat"], tags: ["keeper", "middle-order"], bat: 91, bowl: 2, keep: 94, field: 88, style: "part-time", temperament: 91 },
    { id: "rahul-dravid", name: "Rahul Dravid", country: "India", decade: 2000, roles: ["bat"], tags: ["top-order", "middle-order"], bat: 95, bowl: 6, keep: 12, field: 86, style: "part-time", temperament: 98 },
    { id: "anil-kumble", name: "Anil Kumble", country: "India", decade: 2000, roles: ["bowler", "spinner"], tags: ["spinner"], bat: 42, bowl: 95, keep: 0, field: 78, style: "spin", temperament: 94 },
    { id: "jacques-kallis", name: "Jacques Kallis", country: "South Africa", decade: 2000, roles: ["allrounder", "bat", "bowler"], tags: ["top-order", "allrounder", "pace"], bat: 96, bowl: 86, keep: 0, field: 90, style: "pace", temperament: 98 },
    { id: "shaun-pollock", name: "Shaun Pollock", country: "South Africa", decade: 2000, roles: ["allrounder", "bowler"], tags: ["allrounder", "pace"], bat: 76, bowl: 93, keep: 0, field: 86, style: "pace", temperament: 93 },
    { id: "mark-boucher", name: "Mark Boucher", country: "South Africa", decade: 2000, roles: ["keeper"], tags: ["keeper"], bat: 76, bowl: 2, keep: 95, field: 86, style: "part-time", temperament: 88 },
    { id: "muttiah-muralitharan", name: "Muttiah Muralitharan", country: "Sri Lanka", decade: 2000, roles: ["bowler", "spinner"], tags: ["spinner"], bat: 26, bowl: 100, keep: 0, field: 76, style: "spin", temperament: 96 },
    { id: "kumar-sangakkara", name: "Kumar Sangakkara", country: "Sri Lanka", decade: 2000, roles: ["bat", "keeper"], tags: ["top-order", "keeper"], bat: 96, bowl: 2, keep: 84, field: 84, style: "part-time", temperament: 96 },
    { id: "mahela-jayawardene", name: "Mahela Jayawardene", country: "Sri Lanka", decade: 2000, roles: ["bat"], tags: ["middle-order"], bat: 93, bowl: 8, keep: 0, field: 86, style: "part-time", temperament: 93 },
    { id: "chaminda-vaas", name: "Chaminda Vaas", country: "Sri Lanka", decade: 2000, roles: ["bowler", "allrounder"], tags: ["pace", "allrounder"], bat: 62, bowl: 89, keep: 0, field: 80, style: "pace", temperament: 88 },
    { id: "daniel-vettori", name: "Daniel Vettori", country: "New Zealand", decade: 2000, roles: ["allrounder", "spinner", "bowler"], tags: ["allrounder", "spinner"], bat: 78, bowl: 90, keep: 0, field: 82, style: "spin", temperament: 91 },
    { id: "inzamam-ul-haq", name: "Inzamam-ul-Haq", country: "Pakistan", decade: 2000, roles: ["bat"], tags: ["middle-order"], bat: 91, bowl: 6, keep: 0, field: 68, style: "part-time", temperament: 90 },
    { id: "mohammad-yousuf", name: "Mohammad Yousuf", country: "Pakistan", decade: 2000, roles: ["bat"], tags: ["top-order", "middle-order"], bat: 92, bowl: 5, keep: 0, field: 74, style: "part-time", temperament: 92 },
    { id: "alastair-cook", name: "Alastair Cook", country: "England", decade: 2010, roles: ["bat"], tags: ["opener"], bat: 92, bowl: 4, keep: 0, field: 82, style: "part-time", temperament: 96 },
    { id: "james-anderson", name: "James Anderson", country: "England", decade: 2010, roles: ["bowler"], tags: ["pace"], bat: 20, bowl: 97, keep: 0, field: 78, style: "pace", temperament: 95 },
    { id: "virat-kohli", name: "Virat Kohli", country: "India", decade: 2010, roles: ["bat"], tags: ["top-order", "middle-order"], bat: 94, bowl: 12, keep: 0, field: 92, style: "part-time", temperament: 94 },
    { id: "ms-dhoni", name: "MS Dhoni", country: "India", decade: 2010, roles: ["keeper", "bat"], tags: ["keeper", "middle-order"], bat: 84, bowl: 2, keep: 91, field: 86, style: "part-time", temperament: 93 },
    { id: "ravichandran-ashwin", name: "Ravichandran Ashwin", country: "India", decade: 2010, roles: ["allrounder", "spinner", "bowler"], tags: ["allrounder", "spinner"], bat: 76, bowl: 97, keep: 0, field: 82, style: "spin", temperament: 93 },
    { id: "dale-steyn", name: "Dale Steyn", country: "South Africa", decade: 2010, roles: ["bowler"], tags: ["pace"], bat: 24, bowl: 99, keep: 0, field: 78, style: "pace", temperament: 96 },
    { id: "ab-de-villiers", name: "AB de Villiers", country: "South Africa", decade: 2010, roles: ["bat", "keeper"], tags: ["middle-order", "keeper"], bat: 93, bowl: 8, keep: 80, field: 95, style: "part-time", temperament: 92 },
    { id: "hashim-amla", name: "Hashim Amla", country: "South Africa", decade: 2010, roles: ["bat"], tags: ["top-order"], bat: 93, bowl: 4, keep: 0, field: 80, style: "part-time", temperament: 96 },
    { id: "kane-williamson", name: "Kane Williamson", country: "New Zealand", decade: 2010, roles: ["bat"], tags: ["top-order"], bat: 95, bowl: 28, keep: 0, field: 84, style: "spin", temperament: 97 },
    { id: "brendon-mccullum", name: "Brendon McCullum", country: "New Zealand", decade: 2010, roles: ["keeper", "bat"], tags: ["opener", "keeper"], bat: 86, bowl: 2, keep: 86, field: 90, style: "part-time", temperament: 88 },
    { id: "trent-boult", name: "Trent Boult", country: "New Zealand", decade: 2010, roles: ["bowler"], tags: ["pace"], bat: 24, bowl: 92, keep: 0, field: 82, style: "pace", temperament: 90 },
    { id: "rangana-herath", name: "Rangana Herath", country: "Sri Lanka", decade: 2010, roles: ["bowler", "spinner"], tags: ["spinner"], bat: 30, bowl: 93, keep: 0, field: 76, style: "spin", temperament: 91 },
    { id: "angelo-mathews", name: "Angelo Mathews", country: "Sri Lanka", decade: 2010, roles: ["allrounder", "bat"], tags: ["middle-order", "allrounder"], bat: 86, bowl: 72, keep: 0, field: 82, style: "pace", temperament: 89 },
    { id: "shakib-al-hasan", name: "Shakib Al Hasan", country: "Bangladesh", decade: 2010, roles: ["allrounder", "spinner", "bowler"], tags: ["allrounder", "spinner"], bat: 87, bowl: 88, keep: 0, field: 84, style: "spin", temperament: 90 },
    { id: "mushfiqur-rahim", name: "Mushfiqur Rahim", country: "Bangladesh", decade: 2010, roles: ["keeper", "bat"], tags: ["keeper", "middle-order"], bat: 84, bowl: 2, keep: 82, field: 78, style: "part-time", temperament: 88 },
    { id: "tamim-iqbal", name: "Tamim Iqbal", country: "Bangladesh", decade: 2010, roles: ["bat"], tags: ["opener"], bat: 83, bowl: 4, keep: 0, field: 76, style: "part-time", temperament: 84 },
    { id: "younis-khan", name: "Younis Khan", country: "Pakistan", decade: 2010, roles: ["bat"], tags: ["top-order", "middle-order"], bat: 94, bowl: 8, keep: 0, field: 84, style: "part-time", temperament: 96 },
    { id: "yasir-shah", name: "Yasir Shah", country: "Pakistan", decade: 2010, roles: ["bowler", "spinner"], tags: ["spinner"], bat: 28, bowl: 88, keep: 0, field: 74, style: "spin", temperament: 87 },
    { id: "brendan-taylor", name: "Brendan Taylor", country: "Zimbabwe", decade: 2010, roles: ["bat", "keeper"], tags: ["middle-order", "keeper"], bat: 80, bowl: 4, keep: 76, field: 76, style: "part-time", temperament: 84 },
    { id: "steve-smith", name: "Steve Smith", country: "Australia", decade: 2010, roles: ["bat", "spinner"], tags: ["top-order", "middle-order"], bat: 96, bowl: 42, keep: 0, field: 92, style: "spin", temperament: 97 },
    { id: "nathan-lyon", name: "Nathan Lyon", country: "Australia", decade: 2010, roles: ["bowler", "spinner"], tags: ["spinner"], bat: 26, bowl: 92, keep: 0, field: 78, style: "spin", temperament: 91 },
    { id: "joe-root", name: "Joe Root", country: "England", decade: 2020, roles: ["bat", "spinner"], tags: ["top-order"], bat: 95, bowl: 56, keep: 0, field: 86, style: "spin", temperament: 96 },
    { id: "ben-stokes", name: "Ben Stokes", country: "England", decade: 2020, roles: ["allrounder", "bowler", "bat"], tags: ["middle-order", "allrounder", "pace"], bat: 88, bowl: 84, keep: 0, field: 94, style: "pace", temperament: 94 },
    { id: "pat-cummins", name: "Pat Cummins", country: "Australia", decade: 2020, roles: ["bowler"], tags: ["pace"], bat: 42, bowl: 96, keep: 0, field: 84, style: "pace", temperament: 94 },
    { id: "usman-khawaja", name: "Usman Khawaja", country: "Australia", decade: 2020, roles: ["bat"], tags: ["opener", "top-order"], bat: 89, bowl: 4, keep: 0, field: 78, style: "part-time", temperament: 92 },
    { id: "jasprit-bumrah", name: "Jasprit Bumrah", country: "India", decade: 2020, roles: ["bowler"], tags: ["pace"], bat: 18, bowl: 98, keep: 0, field: 78, style: "pace", temperament: 95 },
    { id: "rishabh-pant", name: "Rishabh Pant", country: "India", decade: 2020, roles: ["keeper", "bat"], tags: ["keeper", "middle-order"], bat: 88, bowl: 2, keep: 84, field: 82, style: "part-time", temperament: 87 },
    { id: "yashasvi-jaiswal", name: "Yashasvi Jaiswal", country: "India", decade: 2020, roles: ["bat"], tags: ["opener"], bat: 87, bowl: 4, keep: 0, field: 82, style: "part-time", temperament: 84 },
    { id: "babar-azam", name: "Babar Azam", country: "Pakistan", decade: 2020, roles: ["bat"], tags: ["top-order"], bat: 90, bowl: 4, keep: 0, field: 82, style: "part-time", temperament: 90 },
    { id: "mohammad-rizwan", name: "Mohammad Rizwan", country: "Pakistan", decade: 2020, roles: ["keeper", "bat"], tags: ["keeper", "middle-order"], bat: 84, bowl: 2, keep: 88, field: 84, style: "part-time", temperament: 89 },
    { id: "kagiso-rabada", name: "Kagiso Rabada", country: "South Africa", decade: 2020, roles: ["bowler"], tags: ["pace"], bat: 30, bowl: 94, keep: 0, field: 82, style: "pace", temperament: 90 },
    { id: "keshav-maharaj", name: "Keshav Maharaj", country: "South Africa", decade: 2020, roles: ["bowler", "spinner"], tags: ["spinner"], bat: 42, bowl: 87, keep: 0, field: 80, style: "spin", temperament: 87 },
    { id: "aiden-markram", name: "Aiden Markram", country: "South Africa", decade: 2020, roles: ["bat", "spinner"], tags: ["opener", "top-order"], bat: 85, bowl: 48, keep: 0, field: 88, style: "spin", temperament: 84 },
    { id: "tim-southee", name: "Tim Southee", country: "New Zealand", decade: 2020, roles: ["bowler"], tags: ["pace"], bat: 42, bowl: 90, keep: 0, field: 80, style: "pace", temperament: 89 },
    { id: "tom-latham", name: "Tom Latham", country: "New Zealand", decade: 2020, roles: ["bat", "keeper"], tags: ["opener", "keeper"], bat: 84, bowl: 2, keep: 82, field: 80, style: "part-time", temperament: 88 },
    { id: "devon-conway", name: "Devon Conway", country: "New Zealand", decade: 2020, roles: ["bat"], tags: ["opener", "top-order"], bat: 86, bowl: 4, keep: 20, field: 82, style: "part-time", temperament: 86 },
    { id: "kyle-jamieson", name: "Kyle Jamieson", country: "New Zealand", decade: 2020, roles: ["bowler", "allrounder"], tags: ["pace", "allrounder"], bat: 62, bowl: 86, keep: 0, field: 80, style: "pace", temperament: 84 },
    { id: "ajaz-patel", name: "Ajaz Patel", country: "New Zealand", decade: 2020, roles: ["bowler", "spinner"], tags: ["spinner"], bat: 20, bowl: 84, keep: 0, field: 74, style: "spin", temperament: 84 },
    { id: "dimuth-karunaratne", name: "Dimuth Karunaratne", country: "Sri Lanka", decade: 2020, roles: ["bat"], tags: ["opener"], bat: 86, bowl: 4, keep: 0, field: 78, style: "part-time", temperament: 89 },
    { id: "dhananjaya-de-silva", name: "Dhananjaya de Silva", country: "Sri Lanka", decade: 2020, roles: ["allrounder", "bat", "spinner"], tags: ["middle-order", "allrounder", "spinner"], bat: 82, bowl: 76, keep: 0, field: 82, style: "spin", temperament: 84 },
    { id: "mehidy-hasan-miraz", name: "Mehidy Hasan Miraz", country: "Bangladesh", decade: 2020, roles: ["allrounder", "spinner", "bowler"], tags: ["allrounder", "spinner"], bat: 72, bowl: 83, keep: 0, field: 82, style: "spin", temperament: 82 },
    { id: "jason-holder", name: "Jason Holder", country: "West Indies", decade: 2020, roles: ["allrounder", "bowler"], tags: ["allrounder", "pace"], bat: 76, bowl: 86, keep: 0, field: 84, style: "pace", temperament: 86 },
    { id: "kemar-roach", name: "Kemar Roach", country: "West Indies", decade: 2010, roles: ["bowler"], tags: ["pace"], bat: 24, bowl: 87, keep: 0, field: 76, style: "pace", temperament: 86 },
    { id: "joshua-da-silva", name: "Joshua Da Silva", country: "West Indies", decade: 2020, roles: ["keeper", "bat"], tags: ["keeper"], bat: 74, bowl: 2, keep: 82, field: 80, style: "part-time", temperament: 80 }
  ]
};
